algoritmo "FLA X FLU"
var
GFA, GFU: Inteiro
inicio
      Escreval ("FLA X FLU")
      Escreva ("Quantos gols do Flamengo? ")
      Leia (GFA)
      Escreva ("Quantos gols do Fluminense? ")
      Leia (GFU)
      Se (GFA>GFU) Entao
         Escreva ("FLAMENGO É CAMPEÃOOOOOOO")
      Senao
           Se (GFU>GFA) Entao
              Escreva ("FLUMINENSE É CAMPEÃOOOOOOO")
           Fimse
      Fimse
fimalgoritmo